# Generated by Django 5.1.1 on 2024-10-26 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "prep_time",
                    models.DurationField(default=datetime.timedelta(seconds=7200)),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "Easy"), (2, "Regular"), (3, "Hard")]
                    ),
                ),
                ("is_veg", models.BooleanField(default=False)),
                ("img", models.ImageField(upload_to="recipes/")),
                ("description", models.TextField()),
            ],
        ),
    ]
